# Generated by Django 4.2.5 on 2023-09-08 13:15

import ckeditor_uploader.fields
from django.db import migrations, models
import django_extensions.db.fields
import tdmvp_back.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='title', verbose_name='Slug')),
                ('image', models.ImageField(upload_to=tdmvp_back.utils.image_upload_to, verbose_name='Изображение')),
                ('short_description', models.CharField(max_length=255, verbose_name='Короткое описание')),
                ('description', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Описание')),
                ('date', models.DateField(verbose_name='Дата публикации')),
                ('is_active', models.BooleanField(default=False, verbose_name='Активность')),
                ('tags', models.ManyToManyField(to='news.newstag', verbose_name='Теги')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ['-id'],
            },
        ),
    ]
