version: '3.9'

services:
  web:
    build: ./
    image: tdmvp_back
    container_name: tdmvp_back
    restart: always
    command: bash entrypoint.sh
    volumes:
      - .:/usr/src/app
      - ./static:/usr/src/app/static
      - ./media:/usr/src/app/media
    ports:
      - 8001:8000
    env_file:
      - ./.env.dev
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: tdmvp_back_db
    volumes:
      - tdmvp_back_postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
    ports:
      - 5433:5432

volumes:
  tdmvp_back_postgres_data: