# Generated by Django 4.2.5 on 2023-09-07 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=255, verbose_name='Цена'),
        ),
    ]
