# Generated by Django 4.2.5 on 2023-09-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='tags',
            field=models.ManyToManyField(to='catalog.producttag', verbose_name='Теги'),
        ),
    ]
